### PR TITLE
update for new prioritizr version

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR is to get prioritizrdata ready for the upcomming changes to the prioritizr package. Briefly, it has updated documentation, updated data (now uses sf and terra classes), and a new example dataset (based on the Washingotn dataset from Hanson et al. 2022 in JAE on connectivity).

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, when you get a chance, could you please review this PR?

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson !
I've gone through the PR updates now and this all looks good to me.
Its great that we now have the WA dataset included as this has loads of good features and the Nolte cost data.

**Comment by jeffreyhanson** [comment]
Awesome - thanks @ricschuster! Since the new versions of prioritizr and prioritizrdata are going to have fairly different docs (e.g., examples will have different code for loading datasets), I suggest we hold off on merging the new versions into the main branches until right before CRAN submissions. How does that sound?

**Comment by ricschuster** [comment]
Sounds great. Thanks very much @jeffreyhanson !

**Comment by jeffreyhanson** [comment]
Since we've just merged the prioritizr PR,  I'll merge this PR for updating prioritizrdata too.

**Comment by ricschuster** [comment]
Just checked the package against winbuilder and macbuilder. All good. 
Should I submit to CRAN now?

**Comment by jeffreyhanson** [comment]
Sorry do you mean prioritizr or prioritizrdata? We need the new version of prioritizr on CRAN before prioritizrdata. If you've checked prioritizr on winbuilder and macbuilder, then yeah, could you please submit prioritizr to CRAN?

**Comment by ricschuster** [comment]
`prioritizrdata`. Still running `prioritizr` checks. Will submit `prioritizr` to CRAN once they come back without issues.

**Pull request merged**
